robots/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :robots
  root 'robots#index'
end

robots/app/models/robot.rb
class Robot < ActiveRecord::Base
end

robots/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

robots/app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  # before_action :load_robot, only: %i(show)

  def index
    @robots = Robot.all
  end

  def show
    @robot = Robot.find(params[:id])
    # We don't need to load the robot here, it's done in the load_robot method
    # @robot = Robot.find(params[:id])

    respond_to do |format|
      format.html {render partial: 'robot'}
      format.json { render json: @robot }
    end
  end

  private
  # load_robot and robot_params are  in the private section because they aren't
  # public actions that can be called by clients of our app,  they only serve as
  # helpers to the public actions

  def load_robot
    @robot = Robot.find(params[:id])
  end

  # Strong Parameters method
  # Removes any keys in the params hash that aren't specified in the permit list
  # This protects us from malicious users hacking our forms
  # Only needed when we're going to *write* to the database
  def robot_params
    params.require(:robot).permit(:name, :address)
  end

end

robots/app/helpers/application_helper.rb
module ApplicationHelper
end

robots/app/helpers/robots_helper.rb
module RobotsHelper
end

robots/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robots</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%#= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.5/handlebars.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

robots/app/views/robots/_robot.html.erb
<%= image_tag "http://robohash.org/#{@robot.address}" %>
<dl>
  <dt>Name</dt>
  <dd><%= @robot.name %></dd>

  <dt>IP Address</dt>
  <dd><%= @robot.address %></dd>

  <dt>Lasers</dt>
  <dd><%= @robot.lasers %></dd>

  <dt>Japanese</dt>
  <dd><%= @robot.japanese %></dd>
</dl>

robots/app/views/robots/index.html.erb
<h1>Robots</h1>

<div id="robot-container" class="robot-box">
  <% @robots.each do |robot| %>
    <article class="robot">
      <%= link_to robot_url(robot) do %>
        <h2><%= robot.name %></h2>
      <% end %>
    </article>
  <% end %>
</div>

<aside id="robot-details-container" class="robot-box">
  <h2>Robot Details</h2>
  <div id="robot-details"></div>
</aside>

robots/app/views/robots/show.html.erb
<%= render partial: 'robot' %>