TaskMaster/config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  resources :todos 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TaskMaster/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TaskMaster/app/models/todo.rb
class Todo < ApplicationRecord
end

TaskMaster/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

TaskMaster/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = Todo.new
    @todos = Todo.all
  end

  def create
    @todo = Todo.new
    @todo.content = params[:todo][:content]
    if @todo.save
     
        puts ".................this request is from fetch"
        respond_to do |format|

          format.html do
            puts ".............response format as html"
            render partial: 'todo', locals:{todo: @todo}
          end
          format.json do 
            puts ".............response format as json"
            render json:@todo
          end

        end
      
    end
  end

  def new
    @todo = Todo.new
  end
end

TaskMaster/app/helpers/application_helper.rb
module ApplicationHelper
end

TaskMaster/app/helpers/todos_helper.rb
module TodosHelper
end

TaskMaster/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMaster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TaskMaster/app/views/todos/_form.html.erb
<%=form_for @todo  do |f|%>

<%= f.text_field :content%>

<%= f.submit data: {disable_with: false}%>

<%end%>

TaskMaster/app/views/todos/_todo.html.erb
<li>
<%=todo.content %></li>

TaskMaster/app/views/todos/create.html.erb
<h1>Todos#create</h1>
<p>Find me in app/views/todos/create.html.erb</p>

TaskMaster/app/views/todos/index.html.erb
<h1>Todos</h1>

<%= link_to('add task' ,new_todo_path)%>
<% if @todos.empty? %>

<p> Sorry! No todos :( </p>

<%else%>

<ul id= 'myList'>
 <%@todos.each do |todo| %>

 <%= render partial: 'todo', locals:{todo: todo} %>
 
 <%end%>
  </ul>
<%= render partial: 'form'%>

<% end %>

TaskMaster/app/views/todos/new.html.erb
<h1>Add new </h1>

<%= render partial: 'form'%>